### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by markbroich** [BobLd/PublayNet-maskrcnn-mlnet#1]
solved

**Comment by BobLd** [comment]
Hi @markbroich,

Unfortunatly, this is the right place to ask this question... What's I've done in the repo is just to use an already trained very specific model that does document segmentation (from [phamquiluan/PubLayNet](https://github.com/phamquiluan/PubLayNet)), convert it to ONNX and use in C# via the ML.Net framework.

This has little to do with what you want to achieve....
